### PR TITLE
[in progress] Serverless offline support

### PR DESCRIPTION
**Pull request by elderapo**
[serverless-offline](https://github.com/dherault/serverless-offline) support so it's easier to test/dev on local machine instead of having to deploy it all the time.

### CODE REVIEW

**Comment by elderapo** [comment]
So far I managed to successfully handle `$connect` and `$disconnect` events. There are some issues with `$default` though. On every `$default` event [this line](https://github.com/michalkvasnicak/aws-lambda-graphql/blob/master/packages/aws-lambda-graphql/src/DynamoDBConnectionManager.ts#L82) throws an error:

```bash
Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1315:34)
    at TLSSocket.emit (events.js:200:13)
    at TLSSocket.EventEmitter.emit (domain.js:471:20)
    at TLSSocket._finishInit (_tls_wrap.js:788:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:605:12) {
  message: 'unable to verify the first certificate',
  code: 'NetworkingError',
  region: 'eu-central-1',
  hostname: 'localhost',
  retryable: true,
  time: 2019-06-19T19:55:10.899Z
}
```

I've tried googling this error and only came across `require('ssl-root-cas').inject()` or `process.env['NODE_TLS_REJECT_UNAUTHORIZED'] = '0';` but unfortunately none of these work.

**Comment by michalkvasnicak** [comment]
Yes it seems that we need to somehow mock the management api to make this work. I don't know if https://github.com/dherault/serverless-offline plans to support it somehow.

Maybe we could abstract it away so this library could be used in other environments and not only AWS.

So perhaps we could have optional `connectionManagementApi` in `DynamoDBConnectionManager` options which defaults to https://github.com/michalkvasnicak/aws-lambda-graphql/blob/master/packages/aws-lambda-graphql/src/DynamoDBConnectionManager.ts#L76

And this could be a part of all connection managers, so you can use them in different environments.

This way we could provide own `connectionManagementApi` and make it backward compatible with what we already have.

**Comment by michalkvasnicak** [comment]
@elderapo any update on this?

**Comment by elderapo** [comment]
Unfortunately no. Also, I don't see myself working on it anytime soon so you can close if you want.

**Comment by michalkvasnicak** [comment]
Closing in favour of #59 

Thank you very much @elderapo for starting point.

**Pull request closed without merging**
