### PR TITLE
Use standard apollo subscription client

### PR DESCRIPTION
**Pull request by AlpacaGoesCrazy**
This allows to use unmodified apollo subscription client with serverless subscriptions
This changes protocol to be compatible with [GraphQL over WebSocket Protocol](https://github.com/apollographql/subscriptions-transport-ws/blob/faa219cff7b6f9873cae59b490da46684d7bea19/PROTOCOL.md)

### CODE REVIEW

**Comment by AlpacaGoesCrazy** [comment]
@michalkvasnicak As this change focuses on the unmodified apollo subscription client should the client part of the package and corresponding tests be removed?

**Comment by michalkvasnicak** [comment]
@AlpacaGoesCrazy does it mean that the server's protocol is no longer compatible? If it isn't compatible, maybe we should abstract the Apollo's client in our client implementation so users won't have problem after upgrade to higher version but recommend them (in README) to use the client from Apollo directly.

**Comment by michalkvasnicak** [comment]
@AlpacaGoesCrazy great work! Is it still in progress or can I merge it? :)

**Comment by AlpacaGoesCrazy** [comment]
@michalkvasnicak  I think after I add ApolloClient integration tests it is good to go

**Comment by michalkvasnicak** [comment]
@AlpacaGoesCrazy ok great, so I'll wait for the tests 👍

**Comment by AlpacaGoesCrazy** [comment]
@michalkvasnicak all done

**Comment by michalkvasnicak** [comment]
Thank you very much, Released as `0.8.0`. I've added a line about your contribution and my next step will be to generate contributors to README using https://github.com/all-contributors/all-contributors

**Comment by michalkvasnicak** [comment]
@AlpacaGoesCrazy great work 👍

**Pull request merged**
