### PR TITLE
Fix missing connection data context in dynamodb event processor

### LINKED ISSUE #64: Set up connection/subscription manager for EventProcessors during Server instantiation
Do not use context to pass them. It's unnecessary. See comment in https://github.com/michalkvasnicak/aws-lambda-graphql/pull/63#issuecomment-571950472

### PR DESCRIPTION
**Pull request by AlpacaGoesCrazy**
Context value from connection.data was not provided for context resolver function in dynamodb event processor. Fix and a test.

Closes #64

### CODE REVIEW

**Comment by AlpacaGoesCrazy** [comment]
Question: Is there a reason to why we are providing connection and subscription managers to `eventProcessor` thru internal context rather than directly?

**Comment by michalkvasnicak** [comment]
That's good question. Yes I can see that. Maybe we could set these during server instantiation:

1. add `setManagers({ connectionManager, subscriptionManager })` method to `IEventProcessor`
2. in `Server.constructor` set it up.

**Comment by michalkvasnicak** [comment]
@AlpacaGoesCrazy Could you please introduce the getters for managers in Server and close the #64 ?

**Comment by AlpacaGoesCrazy** [comment]
@michalkvasnicak done

**Comment by michalkvasnicak** [comment]
@AlpacaGoesCrazy thank you very much.

**Pull request merged**
